python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 1
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 2
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 3
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 4
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 5
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 6
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 7
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 8
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 9
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 10
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 11
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 12
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 13
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 14
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 15
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 16
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 17
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 18
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 19
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 20
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 21
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py 22
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py X
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py Y
python /home/mk446/bio/mutanno/SRC/scripts/precal_vep/s10_vep_stat.py M
