sblong ./s01_fullannot_makedata.sh_01.sh 
sblong ./s01_fullannot_makedata.sh_02.sh 
sblong ./s01_fullannot_makedata.sh_03.sh 
sblong ./s01_fullannot_makedata.sh_04.sh 
sblong ./s01_fullannot_makedata.sh_05.sh 
sblong ./s01_fullannot_makedata.sh_06.sh 
sblong ./s01_fullannot_makedata.sh_07.sh 
sblong ./s01_fullannot_makedata.sh_08.sh 
sblong ./s01_fullannot_makedata.sh_09.sh 
sblong ./s01_fullannot_makedata.sh_10.sh 
sblong ./s01_fullannot_makedata.sh_11.sh 
sblong ./s01_fullannot_makedata.sh_12.sh 
sblong ./s01_fullannot_makedata.sh_13.sh 
sblong ./s01_fullannot_makedata.sh_14.sh 
sblong ./s01_fullannot_makedata.sh_15.sh 
sblong ./s01_fullannot_makedata.sh_16.sh 
sblong ./s01_fullannot_makedata.sh_17.sh 
sblong ./s01_fullannot_makedata.sh_18.sh 
sblong ./s01_fullannot_makedata.sh_19.sh 
sblong ./s01_fullannot_makedata.sh_20.sh 
sblong ./s01_fullannot_makedata.sh_21.sh 
sblong ./s01_fullannot_makedata.sh_22.sh 
sblong ./s01_fullannot_makedata.sh_23.sh 
sblong ./s01_fullannot_makedata.sh_24.sh 
sblong ./s01_fullannot_makedata.sh_25.sh 
sblong ./s01_fullannot_makedata.sh_26.sh 
