sbpark ./tmp_add_na_microannot.sh_01.sh 
sbpark ./tmp_add_na_microannot.sh_02.sh 
sbpark ./tmp_add_na_microannot.sh_03.sh 
sbpark ./tmp_add_na_microannot.sh_04.sh 
sbpark ./tmp_add_na_microannot.sh_05.sh 
sbpark ./tmp_add_na_microannot.sh_06.sh 
sbpark ./tmp_add_na_microannot.sh_07.sh 
sbpark ./tmp_add_na_microannot.sh_08.sh 
sbpark ./tmp_add_na_microannot.sh_09.sh 
sbpark ./tmp_add_na_microannot.sh_10.sh 
sbpark ./tmp_add_na_microannot.sh_11.sh 
sbpark ./tmp_add_na_microannot.sh_12.sh 
sbpark ./tmp_add_na_microannot.sh_13.sh 
sbpark ./tmp_add_na_microannot.sh_14.sh 
sbpark ./tmp_add_na_microannot.sh_15.sh 
sbpark ./tmp_add_na_microannot.sh_16.sh 
sbpark ./tmp_add_na_microannot.sh_17.sh 
sbpark ./tmp_add_na_microannot.sh_18.sh 
sbpark ./tmp_add_na_microannot.sh_19.sh 
sbpark ./tmp_add_na_microannot.sh_20.sh 
sbpark ./tmp_add_na_microannot.sh_21.sh 
sbpark ./tmp_add_na_microannot.sh_22.sh 
sbpark ./tmp_add_na_microannot.sh_23.sh 
sbpark ./tmp_add_na_microannot.sh_24.sh 
sbpark ./tmp_add_na_microannot.sh_25.sh 
