python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 1
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 2
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 3
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 4
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 5
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 6
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 7
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 8
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 9
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 10
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 11
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 12
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 13
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 14
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 15
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 16
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 17
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 18
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 19
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 20
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 21
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py 22
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py X
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py Y
python /home/mk446/mutanno/SRC/scripts/spliceai_maxsc/make_maxsc_spliceai_tsv.py M
